/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BannerTone } from "./components/mrd-banner/mrd-banner";
import { ButtonSize, ButtonType, ButtonVariant } from "./components/mrd-button/mrd-button";
import { DialogCloseReason } from "./components/mrd-dialog/mrd-dialog";
import { TextFieldType } from "./components/mrd-text-field/mrd-text-field";
export { BannerTone } from "./components/mrd-banner/mrd-banner";
export { ButtonSize, ButtonType, ButtonVariant } from "./components/mrd-button/mrd-button";
export { DialogCloseReason } from "./components/mrd-dialog/mrd-dialog";
export { TextFieldType } from "./components/mrd-text-field/mrd-text-field";
export namespace Components {
    /**
     * An inline status message.
     * The one decision that matters here is the ARIA role, and it depends on
     * urgency rather than on tone:
     *   - `danger`  → role="alert"   (assertive; interrupts, for errors the user must act on)
     *   - anything else → role="status" (polite; waits for a pause)
     * Getting this wrong is the commonest accessibility bug in a design system:
     * a success toast with role="alert" cuts off whatever the user was listening to.
     */
    interface MrdBanner {
        /**
          * Accessible name for the dismiss control.
          * @default 'Dismiss message'
         */
        "dismissLabel": string;
        /**
          * Show a dismiss control.
          * @default false
         */
        "dismissible": boolean;
        /**
          * Optional bold heading above the message.
         */
        "heading"?: string;
        /**
          * Announce on mount. Off by default: a banner rendered with the page is part of the page, and announcing it again is noise. Turn on when the banner appears in response to something the user did.
          * @default false
         */
        "live": boolean;
        /**
          * Visual and semantic tone.
          * @default 'info'
         */
        "tone": BannerTone;
    }
    /**
     * A button, or a link that looks like one.
     * Two decisions worth knowing about:
     * 1. `shadow: true`. Styles cannot leak in or out, which is what makes the
     *    component safe to drop into an estate with several competing stylesheets.
     *    The cost is that consumers style it through `::part` and custom properties
     *    only — deliberate, see docs/adr/0003-shadow-dom-and-the-styling-contract.md.
     * 2. When `href` is set we render an `<a>`, not a `<button>` with a click
     *    handler. Screen readers announce the two differently, middle-click and
     *    "open in new tab" only work on a real anchor, and a disabled link is
     *    removed from the tab order rather than faked with `pointer-events: none`.
     */
    interface MrdButton {
        /**
          * Disable interaction. Prefer `loading` for in-flight actions.
          * @default false
         */
        "disabled": boolean;
        /**
          * Stretch to the width of the container.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Render an anchor instead of a button.
         */
        "href"?: string;
        /**
          * Accessible name, when the visible label is not enough — icon-only buttons, or "Edit" repeated down a table where each needs a distinct name.
         */
        "label"?: string;
        /**
          * In-flight state. Keeps the button focusable and announces progress via `aria-busy`, rather than disabling it — a disabled control loses focus, which strands a keyboard user mid-flow.
          * @default false
         */
        "loading": boolean;
        /**
          * Announced while `loading` is true.
          * @default 'Loading'
         */
        "loadingLabel": string;
        /**
          * Move focus to the control.
         */
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * Control height. `sm` still meets the 44px pointer target via a pseudo-element.
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * Anchor target. Adds `rel="noreferrer noopener"` automatically for `_blank`.
         */
        "target"?: '_blank' | '_self' | '_parent' | '_top';
        /**
          * Native button behaviour. Ignored when `href` is set.
          * @default 'button'
         */
        "type": ButtonType;
        /**
          * Visual weight. Use exactly one `primary` per view.
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface MrdDialog {
        /**
          * Accessible name for the close control.
          * @default 'Close dialog'
         */
        "closeLabel": string;
        /**
          * Accessible title. Rendered as the heading unless the `header` slot is used.
         */
        "heading"?: string;
        /**
          * Close the dialog.
         */
        "hide": () => Promise<void>;
        /**
          * Hide the close affordance. Requires `persistent` to be false somewhere else.
          * @default false
         */
        "hideCloseButton": boolean;
        /**
          * CSS selector, resolved inside the dialog, for the element to focus on open. Defaults to the heading, which is what you almost always want.
         */
        "initialFocus"?: string;
        /**
          * Whether the dialog is shown. Two-way via `mrdClose`.
          * @default false
         */
        "open": boolean;
        /**
          * Prevent dismissal by Escape or backdrop click. Use only when losing the dialog would lose the user's work — never merely to keep attention.
          * @default false
         */
        "persistent": boolean;
        /**
          * Open the dialog. Resolves once focus has moved.
         */
        "show": () => Promise<void>;
        /**
          * Visual width.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg' | 'full';
    }
    /**
     * A labelled text input.
     * The interesting part of a text field is not the input, it is the wiring:
     *   - the label is a real `<label for>`, so clicking it focuses the field and
     *     the accessible name is computed by the platform rather than guessed
     *   - hint and error text are joined into `aria-describedby` in a stable order,
     *     so a screen reader reads "Email. Edit text. We'll only use this for
     *     receipts. Enter a valid email address."
     *   - `aria-invalid` is set from the error, not from a separate flag that can
     *     drift out of sync with it
     *   - the error is announced through a live region, so a user who has already
     *     moved on hears it without having to go back
     *   - `formAssociated` makes the component submit with a native form, which a
     *     shadow-DOM input otherwise silently fails to do
     */
    interface MrdTextField {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message. Setting this marks the field invalid and announces it. Empty string or undefined means valid.
         */
        "error"?: string;
        /**
          * Visually hide the label but keep it for assistive technology.
          * @default false
         */
        "hideLabel": boolean;
        /**
          * Supporting text shown under the field, announced before any error.
         */
        "hint"?: string;
        "inputmode"?: 'text' | 'numeric' | 'decimal' | 'email' | 'tel' | 'url' | 'search';
        /**
          * Visible label. Required — a placeholder is not a label.
         */
        "label": string;
        "maxlength"?: number;
        /**
          * Field name for form submission.
         */
        "name"?: string;
        /**
          * Short example of the expected format. Never a substitute for `label`.
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * Select the current value.
         */
        "selectText": () => Promise<void>;
        /**
          * Focus the input.
         */
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * Control height.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Input type. `number` still reports as text to AT for better announcement.
          * @default 'text'
         */
        "type": TextFieldType;
        /**
          * Current value.
          * @default ''
         */
        "value": string;
    }
}
export interface MrdBannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMrdBannerElement;
}
export interface MrdButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMrdButtonElement;
}
export interface MrdDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMrdDialogElement;
}
export interface MrdTextFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMrdTextFieldElement;
}
declare global {
    interface HTMLMrdBannerElementEventMap {
        "mrdDismiss": void;
    }
    /**
     * An inline status message.
     * The one decision that matters here is the ARIA role, and it depends on
     * urgency rather than on tone:
     *   - `danger`  → role="alert"   (assertive; interrupts, for errors the user must act on)
     *   - anything else → role="status" (polite; waits for a pause)
     * Getting this wrong is the commonest accessibility bug in a design system:
     * a success toast with role="alert" cuts off whatever the user was listening to.
     */
    interface HTMLMrdBannerElement extends Components.MrdBanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMrdBannerElementEventMap>(type: K, listener: (this: HTMLMrdBannerElement, ev: MrdBannerCustomEvent<HTMLMrdBannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMrdBannerElementEventMap>(type: K, listener: (this: HTMLMrdBannerElement, ev: MrdBannerCustomEvent<HTMLMrdBannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMrdBannerElement: {
        prototype: HTMLMrdBannerElement;
        new (): HTMLMrdBannerElement;
    };
    interface HTMLMrdButtonElementEventMap {
        "mrdClick": { originalEvent: MouseEvent };
    }
    /**
     * A button, or a link that looks like one.
     * Two decisions worth knowing about:
     * 1. `shadow: true`. Styles cannot leak in or out, which is what makes the
     *    component safe to drop into an estate with several competing stylesheets.
     *    The cost is that consumers style it through `::part` and custom properties
     *    only — deliberate, see docs/adr/0003-shadow-dom-and-the-styling-contract.md.
     * 2. When `href` is set we render an `<a>`, not a `<button>` with a click
     *    handler. Screen readers announce the two differently, middle-click and
     *    "open in new tab" only work on a real anchor, and a disabled link is
     *    removed from the tab order rather than faked with `pointer-events: none`.
     */
    interface HTMLMrdButtonElement extends Components.MrdButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMrdButtonElementEventMap>(type: K, listener: (this: HTMLMrdButtonElement, ev: MrdButtonCustomEvent<HTMLMrdButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMrdButtonElementEventMap>(type: K, listener: (this: HTMLMrdButtonElement, ev: MrdButtonCustomEvent<HTMLMrdButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMrdButtonElement: {
        prototype: HTMLMrdButtonElement;
        new (): HTMLMrdButtonElement;
    };
    interface HTMLMrdDialogElementEventMap {
        "mrdOpen": void;
        "mrdClose": { reason: DialogCloseReason };
    }
    interface HTMLMrdDialogElement extends Components.MrdDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMrdDialogElementEventMap>(type: K, listener: (this: HTMLMrdDialogElement, ev: MrdDialogCustomEvent<HTMLMrdDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMrdDialogElementEventMap>(type: K, listener: (this: HTMLMrdDialogElement, ev: MrdDialogCustomEvent<HTMLMrdDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMrdDialogElement: {
        prototype: HTMLMrdDialogElement;
        new (): HTMLMrdDialogElement;
    };
    interface HTMLMrdTextFieldElementEventMap {
        "mrdInput": { value: string };
        "mrdChange": { value: string };
        "mrdFocus": void;
        "mrdBlur": void;
    }
    /**
     * A labelled text input.
     * The interesting part of a text field is not the input, it is the wiring:
     *   - the label is a real `<label for>`, so clicking it focuses the field and
     *     the accessible name is computed by the platform rather than guessed
     *   - hint and error text are joined into `aria-describedby` in a stable order,
     *     so a screen reader reads "Email. Edit text. We'll only use this for
     *     receipts. Enter a valid email address."
     *   - `aria-invalid` is set from the error, not from a separate flag that can
     *     drift out of sync with it
     *   - the error is announced through a live region, so a user who has already
     *     moved on hears it without having to go back
     *   - `formAssociated` makes the component submit with a native form, which a
     *     shadow-DOM input otherwise silently fails to do
     */
    interface HTMLMrdTextFieldElement extends Components.MrdTextField, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMrdTextFieldElementEventMap>(type: K, listener: (this: HTMLMrdTextFieldElement, ev: MrdTextFieldCustomEvent<HTMLMrdTextFieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMrdTextFieldElementEventMap>(type: K, listener: (this: HTMLMrdTextFieldElement, ev: MrdTextFieldCustomEvent<HTMLMrdTextFieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMrdTextFieldElement: {
        prototype: HTMLMrdTextFieldElement;
        new (): HTMLMrdTextFieldElement;
    };
    interface HTMLElementTagNameMap {
        "mrd-banner": HTMLMrdBannerElement;
        "mrd-button": HTMLMrdButtonElement;
        "mrd-dialog": HTMLMrdDialogElement;
        "mrd-text-field": HTMLMrdTextFieldElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * An inline status message.
     * The one decision that matters here is the ARIA role, and it depends on
     * urgency rather than on tone:
     *   - `danger`  → role="alert"   (assertive; interrupts, for errors the user must act on)
     *   - anything else → role="status" (polite; waits for a pause)
     * Getting this wrong is the commonest accessibility bug in a design system:
     * a success toast with role="alert" cuts off whatever the user was listening to.
     */
    interface MrdBanner {
        /**
          * Accessible name for the dismiss control.
          * @default 'Dismiss message'
         */
        "dismissLabel"?: string;
        /**
          * Show a dismiss control.
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * Optional bold heading above the message.
         */
        "heading"?: string;
        /**
          * Announce on mount. Off by default: a banner rendered with the page is part of the page, and announcing it again is noise. Turn on when the banner appears in response to something the user did.
          * @default false
         */
        "live"?: boolean;
        /**
          * Fired when dismissed.
         */
        "onMrdDismiss"?: (event: MrdBannerCustomEvent<void>) => void;
        /**
          * Visual and semantic tone.
          * @default 'info'
         */
        "tone"?: BannerTone;
    }
    /**
     * A button, or a link that looks like one.
     * Two decisions worth knowing about:
     * 1. `shadow: true`. Styles cannot leak in or out, which is what makes the
     *    component safe to drop into an estate with several competing stylesheets.
     *    The cost is that consumers style it through `::part` and custom properties
     *    only — deliberate, see docs/adr/0003-shadow-dom-and-the-styling-contract.md.
     * 2. When `href` is set we render an `<a>`, not a `<button>` with a click
     *    handler. Screen readers announce the two differently, middle-click and
     *    "open in new tab" only work on a real anchor, and a disabled link is
     *    removed from the tab order rather than faked with `pointer-events: none`.
     */
    interface MrdButton {
        /**
          * Disable interaction. Prefer `loading` for in-flight actions.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Stretch to the width of the container.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Render an anchor instead of a button.
         */
        "href"?: string;
        /**
          * Accessible name, when the visible label is not enough — icon-only buttons, or "Edit" repeated down a table where each needs a distinct name.
         */
        "label"?: string;
        /**
          * In-flight state. Keeps the button focusable and announces progress via `aria-busy`, rather than disabling it — a disabled control loses focus, which strands a keyboard user mid-flow.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Announced while `loading` is true.
          * @default 'Loading'
         */
        "loadingLabel"?: string;
        /**
          * Fired on activation. Not fired while `disabled` or `loading`.
         */
        "onMrdClick"?: (event: MrdButtonCustomEvent<{ originalEvent: MouseEvent }>) => void;
        /**
          * Control height. `sm` still meets the 44px pointer target via a pseudo-element.
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * Anchor target. Adds `rel="noreferrer noopener"` automatically for `_blank`.
         */
        "target"?: '_blank' | '_self' | '_parent' | '_top';
        /**
          * Native button behaviour. Ignored when `href` is set.
          * @default 'button'
         */
        "type"?: ButtonType;
        /**
          * Visual weight. Use exactly one `primary` per view.
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface MrdDialog {
        /**
          * Accessible name for the close control.
          * @default 'Close dialog'
         */
        "closeLabel"?: string;
        /**
          * Accessible title. Rendered as the heading unless the `header` slot is used.
         */
        "heading"?: string;
        /**
          * Hide the close affordance. Requires `persistent` to be false somewhere else.
          * @default false
         */
        "hideCloseButton"?: boolean;
        /**
          * CSS selector, resolved inside the dialog, for the element to focus on open. Defaults to the heading, which is what you almost always want.
         */
        "initialFocus"?: string;
        /**
          * Fired after closing, with the reason.
         */
        "onMrdClose"?: (event: MrdDialogCustomEvent<{ reason: DialogCloseReason }>) => void;
        /**
          * Fired before opening. Cancelable.
         */
        "onMrdOpen"?: (event: MrdDialogCustomEvent<void>) => void;
        /**
          * Whether the dialog is shown. Two-way via `mrdClose`.
          * @default false
         */
        "open"?: boolean;
        /**
          * Prevent dismissal by Escape or backdrop click. Use only when losing the dialog would lose the user's work — never merely to keep attention.
          * @default false
         */
        "persistent"?: boolean;
        /**
          * Visual width.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'full';
    }
    /**
     * A labelled text input.
     * The interesting part of a text field is not the input, it is the wiring:
     *   - the label is a real `<label for>`, so clicking it focuses the field and
     *     the accessible name is computed by the platform rather than guessed
     *   - hint and error text are joined into `aria-describedby` in a stable order,
     *     so a screen reader reads "Email. Edit text. We'll only use this for
     *     receipts. Enter a valid email address."
     *   - `aria-invalid` is set from the error, not from a separate flag that can
     *     drift out of sync with it
     *   - the error is announced through a live region, so a user who has already
     *     moved on hears it without having to go back
     *   - `formAssociated` makes the component submit with a native form, which a
     *     shadow-DOM input otherwise silently fails to do
     */
    interface MrdTextField {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message. Setting this marks the field invalid and announces it. Empty string or undefined means valid.
         */
        "error"?: string;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Visually hide the label but keep it for assistive technology.
          * @default false
         */
        "hideLabel"?: boolean;
        /**
          * Supporting text shown under the field, announced before any error.
         */
        "hint"?: string;
        "inputmode"?: 'text' | 'numeric' | 'decimal' | 'email' | 'tel' | 'url' | 'search';
        /**
          * Visible label. Required — a placeholder is not a label.
         */
        "label": string;
        "maxlength"?: number;
        /**
          * Field name for form submission.
         */
        "name"?: string;
        "onMrdBlur"?: (event: MrdTextFieldCustomEvent<void>) => void;
        /**
          * Fired when the value is committed (blur or Enter).
         */
        "onMrdChange"?: (event: MrdTextFieldCustomEvent<{ value: string }>) => void;
        "onMrdFocus"?: (event: MrdTextFieldCustomEvent<void>) => void;
        /**
          * Fired on each keystroke.
         */
        "onMrdInput"?: (event: MrdTextFieldCustomEvent<{ value: string }>) => void;
        /**
          * Short example of the expected format. Never a substitute for `label`.
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * Control height.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Input type. `number` still reports as text to AT for better announcement.
          * @default 'text'
         */
        "type"?: TextFieldType;
        /**
          * Current value.
          * @default ''
         */
        "value"?: string;
    }

    interface MrdBannerAttributes {
        "tone": BannerTone;
        "heading": string;
        "dismissible": boolean;
        "dismissLabel": string;
        "live": boolean;
    }
    interface MrdButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "type": ButtonType;
        "href": string;
        "target": '_blank' | '_self' | '_parent' | '_top';
        "disabled": boolean;
        "loading": boolean;
        "loadingLabel": string;
        "fullWidth": boolean;
        "label": string;
    }
    interface MrdDialogAttributes {
        "open": boolean;
        "heading": string;
        "size": 'sm' | 'md' | 'lg' | 'full';
        "persistent": boolean;
        "hideCloseButton": boolean;
        "closeLabel": string;
        "initialFocus": string;
    }
    interface MrdTextFieldAttributes {
        "label": string;
        "name": string;
        "type": TextFieldType;
        "value": string;
        "hint": string;
        "error": string;
        "placeholder": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "hideLabel": boolean;
        "size": 'sm' | 'md' | 'lg';
        "autocomplete": string;
        "maxlength": number;
        "inputmode": 'text' | 'numeric' | 'decimal' | 'email' | 'tel' | 'url' | 'search';
    }

    interface IntrinsicElements {
        "mrd-banner": Omit<MrdBanner, keyof MrdBannerAttributes> & { [K in keyof MrdBanner & keyof MrdBannerAttributes]?: MrdBanner[K] } & { [K in keyof MrdBanner & keyof MrdBannerAttributes as `attr:${K}`]?: MrdBannerAttributes[K] } & { [K in keyof MrdBanner & keyof MrdBannerAttributes as `prop:${K}`]?: MrdBanner[K] };
        "mrd-button": Omit<MrdButton, keyof MrdButtonAttributes> & { [K in keyof MrdButton & keyof MrdButtonAttributes]?: MrdButton[K] } & { [K in keyof MrdButton & keyof MrdButtonAttributes as `attr:${K}`]?: MrdButtonAttributes[K] } & { [K in keyof MrdButton & keyof MrdButtonAttributes as `prop:${K}`]?: MrdButton[K] };
        "mrd-dialog": Omit<MrdDialog, keyof MrdDialogAttributes> & { [K in keyof MrdDialog & keyof MrdDialogAttributes]?: MrdDialog[K] } & { [K in keyof MrdDialog & keyof MrdDialogAttributes as `attr:${K}`]?: MrdDialogAttributes[K] } & { [K in keyof MrdDialog & keyof MrdDialogAttributes as `prop:${K}`]?: MrdDialog[K] };
        "mrd-text-field": Omit<MrdTextField, keyof MrdTextFieldAttributes> & { [K in keyof MrdTextField & keyof MrdTextFieldAttributes]?: MrdTextField[K] } & { [K in keyof MrdTextField & keyof MrdTextFieldAttributes as `attr:${K}`]?: MrdTextFieldAttributes[K] } & { [K in keyof MrdTextField & keyof MrdTextFieldAttributes as `prop:${K}`]?: MrdTextField[K] } & OneOf<"label", MrdTextField["label"], MrdTextFieldAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * An inline status message.
             * The one decision that matters here is the ARIA role, and it depends on
             * urgency rather than on tone:
             *   - `danger`  → role="alert"   (assertive; interrupts, for errors the user must act on)
             *   - anything else → role="status" (polite; waits for a pause)
             * Getting this wrong is the commonest accessibility bug in a design system:
             * a success toast with role="alert" cuts off whatever the user was listening to.
             */
            "mrd-banner": LocalJSX.IntrinsicElements["mrd-banner"] & JSXBase.HTMLAttributes<HTMLMrdBannerElement>;
            /**
             * A button, or a link that looks like one.
             * Two decisions worth knowing about:
             * 1. `shadow: true`. Styles cannot leak in or out, which is what makes the
             *    component safe to drop into an estate with several competing stylesheets.
             *    The cost is that consumers style it through `::part` and custom properties
             *    only — deliberate, see docs/adr/0003-shadow-dom-and-the-styling-contract.md.
             * 2. When `href` is set we render an `<a>`, not a `<button>` with a click
             *    handler. Screen readers announce the two differently, middle-click and
             *    "open in new tab" only work on a real anchor, and a disabled link is
             *    removed from the tab order rather than faked with `pointer-events: none`.
             */
            "mrd-button": LocalJSX.IntrinsicElements["mrd-button"] & JSXBase.HTMLAttributes<HTMLMrdButtonElement>;
            "mrd-dialog": LocalJSX.IntrinsicElements["mrd-dialog"] & JSXBase.HTMLAttributes<HTMLMrdDialogElement>;
            /**
             * A labelled text input.
             * The interesting part of a text field is not the input, it is the wiring:
             *   - the label is a real `<label for>`, so clicking it focuses the field and
             *     the accessible name is computed by the platform rather than guessed
             *   - hint and error text are joined into `aria-describedby` in a stable order,
             *     so a screen reader reads "Email. Edit text. We'll only use this for
             *     receipts. Enter a valid email address."
             *   - `aria-invalid` is set from the error, not from a separate flag that can
             *     drift out of sync with it
             *   - the error is announced through a live region, so a user who has already
             *     moved on hears it without having to go back
             *   - `formAssociated` makes the component submit with a native form, which a
             *     shadow-DOM input otherwise silently fails to do
             */
            "mrd-text-field": LocalJSX.IntrinsicElements["mrd-text-field"] & JSXBase.HTMLAttributes<HTMLMrdTextFieldElement>;
        }
    }
}
