/**
 * Public type surface for `@meridian/components`.
 *
 * The runtime entry points are generated by Stencil (`dist/`, `loader/`,
 * `dist/components/`). This file exists so consumers can import the union types
 * that make up each component's contract without reaching into `components.d.ts`,
 * which Stencil rewrites on every build.
 */

export type { ButtonVariant, ButtonSize, ButtonType } from './components/mrd-button/mrd-button';
export type { TextFieldType } from './components/mrd-text-field/mrd-text-field';
export type { BannerTone } from './components/mrd-banner/mrd-banner';

export { getFocusableElements, FocusTrap, RovingTabindex } from './utils/focus';
export { lockScroll, unlockScroll } from './utils/scroll-lock';

export { Components, JSX } from './components';
